stages:
  - mirror
  - build
  - deploy

.dockertag: &dockertag
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        DOCKERTAG: "latest"
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        DOCKERTAG: "${CI_COMMIT_REF_NAME}"

Mirror to github:
  stage: mirror

  image: haffmans/git-mirror:latest
  script:
  - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}

Build:
  <<: *dockertag
  stage: build
  script:
  - docker build --tag=${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${DOCKERTAG} .
  tags:
  - docker

Push to Hub:
  <<: *dockertag
  stage: deploy
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_TOKEN}
  - docker push ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${DOCKERTAG}
  tags:
  - docker
