stages:
  - mirror
  - build
  - deploy

Mirror to github:
  stage: mirror

  script:
  - mkdir -p $HOME/.ssh
  - echo "${GITHUB_DEPLOY_KEY}" > $HOME/.ssh/github
  - chmod 0600 $HOME/.ssh/github
  - mv $HOME/.ssh/config $HOME/.ssh/config~ || /bin/true
  - echo "host github.com" > $HOME/.ssh/config
  - echo "  IdentityFile %d/.ssh/github" >> $HOME/.ssh/config
  - echo "  PubKeyAuthentication yes" >> $HOME/.ssh/config

  - git remote add --mirror=push github git@github.com:${GITHUB_REPOSITORY} || /bin/true
  - git push github

  after_script:
  - mv $HOME/.ssh/config~ $HOME/.ssh/config || /bin/true
  - rm $HOME/.ssh/github

Build master:
  stage: build
  script:
  - docker rmi --force ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:latest || /bin/true
  - docker build --no-cache --tag=${DOCKERHUB_USER}/${DOCKERHUB_REPO}:latest .
  tags:
  - docker
  only:
  - master

Build other:
  stage: build
  script:
  - docker build --no-cache --tag=${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${CI_BUILD_REF_NAME} .
  tags:
  - docker
  except:
  - master

# Note: to be friendly to Docker Hub, the auto-update on push is disabled in Docker hub.
# The repository itself is mirrored to GitHub immediately on every push.
Build branch on Docker Hub:
  stage: deploy
  script:
  - 'curl -H "Content-Type: application/json" --data "{\"source_type\": \"Branch\", \"source_name\": \"${CI_BUILD_REF_NAME}\"}" -X POST https://registry.hub.docker.com/u/${DOCKERHUB_USER}/${DOCKERHUB_REPO}/trigger/${DOCKERHUB_TOKEN}/'
  except:
  - tags

Build tag on Docker Hub:
  stage: deploy
  script:
  - 'curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"${CI_BUILD_REF_NAME}\"}" -X POST https://registry.hub.docker.com/u/${DOCKERHUB_USER}/${DOCKERHUB_REPO}/trigger/${DOCKERHUB_TOKEN}/'
  except:
  - branches
